---
title: "infercnv_analysis"
author: "Kevin Stachelek"
date: "4/14/2022"
output: html_document
params:
  data_dir: "what"
  normal_reference_mat: "what"
  annotations: "what"
  counts_path: "what"
  out_dir: "what"
---

```{r setup, echo = F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```


```{r load-packages}
library(glue)
library(fs)
library(rprojroot)
library(tidyverse)
library(seuratTools)
proj_dir = rprojroot::find_root(criterion = has_file_pattern("*.Rproj"))
library(infercnv)
```

```{r}

# data_dir = "../data/SRR13884240/"

count_mat <- Seurat::Read10X(data_dir) %>% 
	identity()

# ref_counts <- readRDS("../output/infercnv/reference_counts.rds")

ref_counts <- readRDS(normal_reference_mat) %>% 
	identity()

combine_matrices <- function(exp_mat, reference_mat){
	exp_names <- rownames(exp_mat)
	reference_names <- rownames(reference_mat)
	shared_names <- intersect(exp_names, reference_names)
	
	exp_mat <- exp_mat[shared_names,]
	reference_mat <- reference_mat[shared_names,]
	
	colnames(reference_mat) <- paste0("normal_", colnames(reference_mat))
	
	common_mat <- cbind(exp_mat, reference_mat)
	
}

combined_count_mat <- combine_matrices(count_mat, ref_counts)


```
# create infercnv object 

```{r }

# create annotations files 
annotations <- 
  colnames(combined_count_mat) %>%
	as_tibble_col(column_name = "sample_id") %>%
	dplyr::mutate(annotation = ifelse(str_detect(sample_id, "normal"), "normal", "rb_tumor")) %>%
	identity()

# annotations_path <- fs::path(proj_dir, "output/infercnv/annotations_file.tsv") 
annotations_path <- fs::path(annotations)

write.table(annotations, annotations_path, sep = "\t", row.names = FALSE, col.names = FALSE)

```

```{r, eval = TRUE}

# annotables_selected <- 
#   annotables::grch38 %>% 
#   dplyr::select(symbol, ensgene)

gene_order_file="~/Homo_sapiens/grch38_tran/Homo_sapiens.GRCh38.87.gene_pos.txt" %>% 
  read_tsv(col_names = c("symbol", "seqnames", "start", "end")) %>% 
  dplyr::filter(seqnames %in% c(1:22, "X", "Y", "MT")) %>%
  identity()

combined_count_mat <- combined_count_mat[rownames(combined_count_mat) %in% gene_order_file$symbol,]

# counts_path <- fs::path(proj_dir, "output/infercnv/gene_matrix.tsv")

# fs::file_delete(counts_path)
write.table(combined_count_mat, counts_path, sep = "\t")

```

```{r }

infercnv_obj  <- CreateInfercnvObject(raw_counts_matrix=counts_path, annotations_file=annotations_path, delim = "\t", gene_order_file="~/Homo_sapiens/grch38_tran/Homo_sapiens.GRCh38.87.gene_pos.txt", ref_group_names = "normal")

```

# run infercnv

```{r, message = FALSE, eval = FALSE}
# debug(infercnv::plot_cnv)
infercnv_obj  <- infercnv::run(infercnv_obj, 
                               analysis_mode='subclusters', 
                               cutoff = 0.1, # cutoff=1 works well for Smart-seq2, and cutoff=0.1 works well for 10x Genomics
                               out_dir = out_dir, 
                               cluster_by_groups= TRUE, 
                               denoise = TRUE, 
                               HMM = TRUE,
                               debug = TRUE)

```

```{r}
plot_cnv(infercnv_obj, 
         # plot_chr_scale = TRUE, 
         output_format = "pdf",
         write_expr_matrix = TRUE)
```

