#!/bin/bash
# Usage: sbatch src/run_cellranger_aggr.sub <csv_path> <id>
#SBATCH --job-name=snakemake_smallRNA
#SBATCH -A SBSANDME_LAB
#SBATCH -p standard
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=6G
#SBATCH --time=08:00:00
#SBATCH --error=logs/snakemake_master.%j.err
#SBATCH --output=logs/snakemake_master.%j.out


module load cellranger/8.0.1
rm -rf "$2"
cellranger aggr --normalize none --id "$2" --csv "$1"
module unload cellranger/8.0.1
